package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/alecthomas/kong"
)

// Options controls how documentation is generated.
type Options struct {
	// AppName overrides the application name in generated docs.
	// Defaults to the Kong model name.
	AppName string

	// AppDescription is the top-level description for the index page.
	AppDescription string
}

// Generate walks the Kong application model and writes one Markdown file per
// command to outDir. It also writes an index file (<appname>.md).
// Hidden commands are skipped.
func Generate(app *kong.Application, outDir string, opts Options) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	name := opts.AppName
	if name == "" {
		name = app.Name
	}

	// Collect all nodes to generate docs for.
	var nodes []*kong.Node
	collectNodes(app.Node, &nodes)

	// Write per-command files.
	for _, node := range nodes {
		if err := writeNodeFile(outDir, name, node); err != nil {
			return err
		}
	}

	// Write the index file.
	return writeIndex(outDir, name, opts.AppDescription, app.Node, nodes)
}

// collectNodes recursively gathers non-hidden command nodes.
func collectNodes(node *kong.Node, out *[]*kong.Node) {
	for _, child := range node.Children {
		if child.Hidden {
			continue
		}
		*out = append(*out, child)
		collectNodes(child, out)
	}
}

// slug returns the Markdown filename for a node, e.g. "fat-controller_config_get.md".
func slug(appName string, node *kong.Node) string {
	parts := make([]string, 0, 4)
	parts = append(parts, appName)
	parts = append(parts, pathParts(node)...)
	return strings.Join(parts, "_") + ".md"
}

// pathParts returns the command path segments from root to node (excluding the app).
func pathParts(node *kong.Node) []string {
	if node.Parent == nil || node.Type == kong.ApplicationNode {
		return nil
	}
	return append(pathParts(node.Parent), node.Name)
}

// fullPath returns "appname cmd subcmd".
func fullPath(appName string, node *kong.Node) string {
	parts := make([]string, 0, 4)
	parts = append(parts, appName)
	parts = append(parts, pathParts(node)...)
	return strings.Join(parts, " ")
}

// generatedNotice is prepended to every generated file.
const generatedNotice = "<!-- Generated by internal/tools/docgen. DO NOT EDIT. -->\n\n"

// writeNodeFile generates a Markdown reference page for a single command.
func writeNodeFile(outDir, appName string, node *kong.Node) error {
	var buf bytes.Buffer
	buf.WriteString(generatedNotice)
	fp := fullPath(appName, node)

	// Title
	fmt.Fprintf(&buf, "# %s\n\n", fp)

	// Short description
	if node.Help != "" {
		fmt.Fprintf(&buf, "%s\n\n", node.Help)
	}

	// Synopsis
	fmt.Fprintf(&buf, "## Synopsis\n\n")
	fmt.Fprintf(&buf, "```text\n%s", fp)
	writeUsageSuffix(&buf, node)
	fmt.Fprintf(&buf, "\n```\n\n")

	// Description (detail)
	if node.Detail != "" {
		fmt.Fprintf(&buf, "## Description\n\n%s\n\n", node.Detail)
	}

	// Positional arguments
	if len(node.Positional) > 0 {
		fmt.Fprintf(&buf, "## Arguments\n\n")
		for _, pos := range node.Positional {
			req := ""
			if pos.Required {
				req = " **(required)**"
			}
			fmt.Fprintf(&buf, "- `<%s>`%s", pos.Name, req)
			if pos.Help != "" {
				fmt.Fprintf(&buf, " — %s", pos.Help)
			}
			fmt.Fprintf(&buf, "\n")
		}
		fmt.Fprintf(&buf, "\n")
	}

	// Command-specific flags (not inherited from parent/root)
	localFlags := nonHiddenFlags(node.Flags)
	if len(localFlags) > 0 {
		fmt.Fprintf(&buf, "## Flags\n\n")
		writeFlagTable(&buf, localFlags)
	}

	// Inherited (global) flags — flags from ancestors
	inherited := inheritedFlags(node)
	if len(inherited) > 0 {
		fmt.Fprintf(&buf, "## Global Flags\n\n")
		writeFlagTable(&buf, inherited)
	}

	// Subcommands
	var children []*kong.Node
	for _, child := range node.Children {
		if !child.Hidden {
			children = append(children, child)
		}
	}
	if len(children) > 0 {
		fmt.Fprintf(&buf, "## Commands\n\n")
		for _, child := range children {
			link := slug(appName, child)
			fmt.Fprintf(&buf, "- [%s](%s) — %s\n", fullPath(appName, child), link, child.Help)
		}
		fmt.Fprintf(&buf, "\n")
	}

	// See also
	fmt.Fprintf(&buf, "## See Also\n\n")
	if node.Parent != nil && node.Parent.Type != kong.ApplicationNode {
		fmt.Fprintf(&buf, "- [%s](%s) — %s\n",
			fullPath(appName, node.Parent),
			slug(appName, node.Parent),
			node.Parent.Help)
	} else {
		fmt.Fprintf(&buf, "- [%s](%s.md) — top-level reference\n", appName, appName)
	}
	fmt.Fprintf(&buf, "\n")

	path := filepath.Join(outDir, slug(appName, node))
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

// writeIndex generates the root index page listing all commands.
func writeIndex(outDir, appName, description string, root *kong.Node, nodes []*kong.Node) error {
	var buf bytes.Buffer
	buf.WriteString(generatedNotice)

	fmt.Fprintf(&buf, "# %s\n\n", appName)

	if description != "" {
		fmt.Fprintf(&buf, "%s\n\n", description)
	}

	// Synopsis
	fmt.Fprintf(&buf, "## Synopsis\n\n")
	fmt.Fprintf(&buf, "```text\n%s <command> [flags]\n```\n\n", appName)

	// Global flags
	globalFlags := nonHiddenFlags(root.Flags)
	if len(globalFlags) > 0 {
		fmt.Fprintf(&buf, "## Global Flags\n\n")
		writeFlagTable(&buf, globalFlags)
	}

	// Command listing
	fmt.Fprintf(&buf, "## Commands\n\n")

	// Group by top-level command group.
	type group struct {
		parent *kong.Node
		leaves []*kong.Node
	}
	groups := map[string]*group{}
	var groupOrder []string
	for _, node := range nodes {
		// Only list leaf commands.
		if len(node.Children) > 0 {
			continue
		}
		topParts := pathParts(node)
		if len(topParts) == 0 {
			continue
		}
		key := topParts[0]
		if _, ok := groups[key]; !ok {
			// Find the top-level parent node.
			var parent *kong.Node
			for _, child := range root.Children {
				if child.Name == key {
					parent = child
					break
				}
			}
			groups[key] = &group{parent: parent}
			groupOrder = append(groupOrder, key)
		}
		groups[key].leaves = append(groups[key].leaves, node)
	}

	sort.Strings(groupOrder)
	for _, key := range groupOrder {
		g := groups[key]
		title := key
		if g.parent != nil && g.parent.Help != "" {
			title = fmt.Sprintf("%s — %s", key, g.parent.Help)
		}
		fmt.Fprintf(&buf, "### %s\n\n", title)
		for _, node := range g.leaves {
			fmt.Fprintf(&buf, "- [%s](%s) — %s\n", fullPath(appName, node), slug(appName, node), node.Help)
		}
		fmt.Fprintf(&buf, "\n")
	}

	path := filepath.Join(outDir, appName+".md")
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

// writeUsageSuffix appends positional args and [flags]/[command] to the usage line.
func writeUsageSuffix(buf *bytes.Buffer, node *kong.Node) {
	for _, pos := range node.Positional {
		if pos.Required {
			fmt.Fprintf(buf, " <%s>", pos.Name)
		} else {
			fmt.Fprintf(buf, " [<%s>]", pos.Name)
		}
	}
	hasChildren := false
	for _, child := range node.Children {
		if !child.Hidden {
			hasChildren = true
			break
		}
	}
	if hasChildren {
		fmt.Fprintf(buf, " <command>")
	}
	fmt.Fprintf(buf, " [flags]")
}

// writeFlagTable writes a Markdown table of flags.
func writeFlagTable(buf *bytes.Buffer, flags []*kong.Flag) {
	fmt.Fprintf(buf, "| Flag | Type | Default | Env | Description |\n")
	fmt.Fprintf(buf, "|------|------|---------|-----|-------------|\n")
	for _, flag := range flags {
		short := ""
		if flag.Short != 0 {
			short = fmt.Sprintf("`-%s`, ", string(flag.Short))
		}
		name := fmt.Sprintf("%s`--%s`", short, flag.Name)

		typ := flagType(flag)

		def := ""
		if flag.HasDefault {
			def = fmt.Sprintf("`%s`", flag.Default)
		}

		env := ""
		if len(flag.Envs) > 0 {
			parts := make([]string, len(flag.Envs))
			for i, e := range flag.Envs {
				parts[i] = fmt.Sprintf("`%s`", e)
			}
			env = strings.Join(parts, ", ")
		}

		help := strings.ReplaceAll(flag.Help, "|", "\\|")

		fmt.Fprintf(buf, "| %s | %s | %s | %s | %s |\n", name, typ, def, env, help)
	}
	fmt.Fprintf(buf, "\n")
}

// Well-known reflect types for flag type detection.
var (
	durationType = reflect.TypeOf(time.Duration(0))
	intType      = reflect.TypeOf(int(0))
	int64Type    = reflect.TypeOf(int64(0))
)

// flagType returns a human-readable type string for a flag.
func flagType(flag *kong.Flag) string {
	if flag.IsBool() {
		return "bool"
	}
	if flag.Enum != "" {
		vals := strings.Split(flag.Enum, ",")
		return strings.Join(vals, "\\|")
	}
	if flag.IsSlice() {
		return "string[]"
	}

	// Compare the underlying Go type against well-known types, since
	// FormatPlaceHolder() returns the default value for durations.
	switch flag.Target.Type() {
	case durationType:
		return "duration"
	case intType, int64Type:
		return "int"
	default:
		return "string"
	}
}

// nonHiddenFlags returns flags from the given slice that are not hidden,
// and excludes the built-in help flag.
func nonHiddenFlags(flags []*kong.Flag) []*kong.Flag {
	var out []*kong.Flag
	for _, flag := range flags {
		if flag.Hidden || flag.Name == "help" {
			continue
		}
		out = append(out, flag)
	}
	return out
}

// inheritedFlags collects non-hidden flags from all ancestor nodes.
func inheritedFlags(node *kong.Node) []*kong.Flag {
	var out []*kong.Flag
	seen := map[string]bool{}

	// Mark this node's own flags.
	for _, f := range node.Flags {
		seen[f.Name] = true
	}

	// Walk ancestors and collect their flags.
	for parent := node.Parent; parent != nil; parent = parent.Parent {
		for _, f := range parent.Flags {
			if f.Hidden || f.Name == "help" || seen[f.Name] {
				continue
			}
			seen[f.Name] = true
			out = append(out, f)
		}
	}
	return out
}
