name = "production"
variables = { MEILI_MASTER_KEY = "${MEILI_MASTER_KEY}" }

[workspace]
name = "Hamish Morgan's Projects"

[project]
name = "Life"

[[service]]
name = "embeddings"
variables = { MAX_CLIENT_BATCH_SIZE = "32", MODEL_ID = "BAAI/bge-small-en-v1.5", PORT = "8090" }

[[service]]
name = "hanko"

[service.variables]
HANKO_DB_HOST = "${{postgres.RAILWAY_PRIVATE_DOMAIN}}"
HANKO_DB_PASSWORD = "${{postgres.POSTGRES_PASSWORD}}"
HANKO_DB_PORT = "${{postgres.PGPORT}}"
HANKO_DB_USER = "${{postgres.POSTGRES_USER}}"
HANKO_SECRET_KEY = "${HANKO_SECRET_KEY}"
PORT = "8000"
SMTP_HOST = "smtp.resend.com"
SMTP_PASSWORD = "${SMTP_PASSWORD}"
SMTP_PORT = "2587"
SMTP_USER = "resend"

[[service]]
name = "meilisearch"

[service.variables]
MEILI_DB_PATH = "/meili_data/data.ms"
MEILI_ENV = "production"
MEILI_MASTER_KEY = "${{shared.MEILI_MASTER_KEY}}"
MEILI_MAX_INDEXING_MEMORY = "512Mb"
MEILI_MAX_INDEXING_THREADS = "2"
MEILI_MAX_THREADS = "2"
PORT = "7700"

[[service]]
name = "postgres"

[service.variables]
DATABASE_PUBLIC_URL = "postgresql://${{PGUSER}}:${{POSTGRES_PASSWORD}}@${{RAILWAY_TCP_PROXY_DOMAIN}}:${{RAILWAY_TCP_PROXY_PORT}}/${{PGDATABASE}}"
DATABASE_URL = "postgresql://${{PGUSER}}:${{POSTGRES_PASSWORD}}@${{RAILWAY_PRIVATE_DOMAIN}}:5432/${{PGDATABASE}}"
PGDATA = "/var/lib/postgresql/data/pgdata"
PGDATABASE = "${{POSTGRES_DB}}"
PGHOST = "${{RAILWAY_PRIVATE_DOMAIN}}"
PGPASSWORD = "${{POSTGRES_PASSWORD}}"
PGPORT = "5432"
PGUSER = "${{POSTGRES_USER}}"
POSTGRES_DB = "railway"
POSTGRES_PASSWORD = "${POSTGRES_PASSWORD}"
POSTGRES_USER = "postgres"
RAILWAY_DEPLOYMENT_DRAINING_SECONDS = "60"
SSL_CERT_DAYS = "820"

[[service]]
name = "proxy"
variables = { HANKO_PORT = "${{hanko.PORT}}", SERVER_PORT = "${{server.PORT}}", WEB_PORT = "8080" }

[[service]]
name = "server"

[service.variables]
APP_ENV = "production"
DATABASE_URL = "postgresql://${{postgres.PGUSER}}:${{postgres.PGPASSWORD}}@${{postgres.PGHOST}}:${{postgres.PGPORT}}/${{postgres.PGDATABASE}}"
HANKO_API_URL = "http://hanko.railway.internal:${{hanko.PORT}}"
MEILI_EMBEDDING_URL = "http://embeddings.railway.internal:8090"
MEILI_MASTER_KEY = "${{shared.MEILI_MASTER_KEY}}"
MEILI_URL = "http://meilisearch.railway.internal:7700"
SERVER_PORT = "8080"

[[service]]
name = "web"
variables = { VITE_HANKO_API_URL = "https://life.hamish.lol/auth" }
