// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package railway

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// ProjectTokenProjectToken includes the requested fields of the GraphQL type ProjectToken.
type ProjectTokenProjectToken struct {
	ProjectId     string `json:"projectId"`
	EnvironmentId string `json:"environmentId"`
}

// GetProjectId returns ProjectTokenProjectToken.ProjectId, and is useful for accessing the field via an interface.
func (v *ProjectTokenProjectToken) GetProjectId() string { return v.ProjectId }

// GetEnvironmentId returns ProjectTokenProjectToken.EnvironmentId, and is useful for accessing the field via an interface.
func (v *ProjectTokenProjectToken) GetEnvironmentId() string { return v.EnvironmentId }

// ProjectTokenResponse is returned by ProjectToken on success.
type ProjectTokenResponse struct {
	// Get a single project token by the value in the header
	ProjectToken ProjectTokenProjectToken `json:"projectToken"`
}

// GetProjectToken returns ProjectTokenResponse.ProjectToken, and is useful for accessing the field via an interface.
func (v *ProjectTokenResponse) GetProjectToken() ProjectTokenProjectToken { return v.ProjectToken }

// The query executed by ProjectToken.
const ProjectToken_Operation = `
query ProjectToken {
	projectToken {
		projectId
		environmentId
	}
}
`

// ProjectToken resolves a project-scoped token to its project and environment IDs.
// Used by auth status and as a basic connectivity check.
func ProjectToken(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *ProjectTokenResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ProjectToken",
		Query:  ProjectToken_Operation,
	}

	data_ = &ProjectTokenResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
