[tasks.lint]
description = "Run all linters"
depends = ["lint:md"]

[tasks.check]
description = "Run all linters and checks"
depends = ["lint"]

[tasks.format]
description = "Run all fixers/formatters"
depends = ["lint:md:fix"]

[tasks."lint:md"]
description = "Lint markdown files"
run = "npx --yes markdownlint-cli2 --config .config/.markdownlint-cli2.jsonc '**/*.md' '#node_modules'"

[tasks."lint:md:fix"]
description = "Lint and fix markdown files"
run = "npx --yes markdownlint-cli2 --config .config/.markdownlint-cli2.jsonc --fix '**/*.md' '#node_modules'"
